name: Makefile CI

on:
  push:
    branches: [ stable , dev ]
  pull_request:
    branches: [ stable , dev ]

jobs:
  test-with-gcc-5-ubuntu18:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    
    - name: install dependencies
      run: sudo apt-get install -y wget gfortran-5 gcc-5 g++-5
    
    - name: configure
      run: >
        export CC=gcc-5; export CXX=g++-5; export FC=gfortran-5; 
        ./configure --with-par=b1m --enable-simd=sse --enable-mcmodel=large --disable-mpi --disable-gpu
      
    - name: make
      run: make clean; make
      
    - name: prepare simulation
      run: >
        mkdir autotest; 
        cp -p ./build/nbody6++.sse ./autotest/; 
        cd autotest; 
        wget https://github.com/kaiwu-astro/garage/raw/main/Nbody6ppGPU-inputfile/kepler_100k_test/100k.inp; 
        pwd; ls -alh
    
    - name: simulation
      run: ulimit -s unlimited; cd autotest; ./nbody6++.sse < 100k.inp
      
  test-with-latest:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: install dependencies
      run: sudo apt-get install -y wget gfortran gcc g++
    
    - name: configure
      run: >
        ./configure --with-par=b1m --enable-simd=sse --enable-mcmodel=large --disable-mpi --disable-gpu
      
    - name: make
      run: make clean; make
      
    - name: prepare simulation
      run: >
        mkdir autotest; 
        cp -p ./build/nbody6++.sse ./autotest/; 
        cd autotest; 
        wget https://github.com/kaiwu-astro/garage/raw/main/Nbody6ppGPU-inputfile/kepler_100k_test/100k.inp; 
        pwd; ls -alh
    
    - name: simulation
      run: ulimit -s unlimited; cd autotest; ./nbody6++.sse < 100k.inp
