name: Makefile CI

on:
  push:
    branches: [ stable , dev ]
  pull_request:
    branches: [ stable , dev ]

jobs:
  test-small-simulation:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    
    - name: install dependencies
      run: sudo apt-get install -y gfortran-5 gcc-5 g++-5
    
    - name: configure
      run: export CC=gcc-5; export CXX=g++-5; export FC=gfortran-5; ./configure --with-par=b1m --enable-simd=sse --enable-mcmodel=large --disable-mpi --disable-gpu
      
    - name: make
      run: make clean; make
      
    - name: prepare simulation
      run: mkdir autotest; cp -p ./build/nbody6++.sse ./autotest/; cd autotest; echo -e "1 1.0E8 1.0 40 40 0 \n100000 1 10 43532  80 1 10 \n0.01 0.01 0.15 1.0 1.0 100.0 1.0 1.0 0.7 \n0 1 1 0 1 0 4 0 0 2 \n0 1 0 2 2 0 0 0 3 6 \n1 0 2 0 0 2 0 0 0 2 \n1 0 2 1 1 0 1 1 2 0 \n0 0 0 0 0 2 3 0 1 0 \n2.5E-6 8.E-5 0.1 1.0 1.0E-06 0.01 0.125 \n2.35 150.0 0.08 0 0 0.001 0 1.0 \n0.5 0.0 0.0 0.0 \n1.78E11 13.3" > input.txt; pwd; ls -alh
    
    - name: simulation
      run: ulimit -s unlimited; cd autotest; ./nbody6++.sse < input.txt
